# Generated by Django 4.1.5 on 2023-01-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_users_apellidos_remove_users_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservationsRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('people', models.IntegerField()),
                ('allergy', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=30),
        ),
    ]
