# Generated by Django 4.1.5 on 2023-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservationsrestaurant_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsrestaurant',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
