# Generated by Django 4.1.5 on 2023-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_typeroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Bus stop')),
                ('address', models.CharField(max_length=250, verbose_name='Bus stop address')),
                ('latitude', models.FloatField(verbose_name='Bus stop latitude')),
                ('longitude', models.FloatField(verbose_name='Bus stop longitude')),
            ],
            options={
                'verbose_name': 'Bus stop',
                'ordering': ['name'],
            },
        ),
    ]
