# Generated by Django 4.1.5 on 2023-02-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeroomhotel',
            options={'ordering': ['type'], 'verbose_name': 'Type room'},
        ),
        migrations.AlterField(
            model_name='typeroomhotel',
            name='type',
            field=models.CharField(default=0, max_length=50, verbose_name='Type room'),
        ),
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('newPrice', models.IntegerField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('typeRoom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.typeroomhotel')),
            ],
            options={
                'ordering': ['typeRoom'],
            },
        ),
    ]
