# Generated by Django 4.1.5 on 2023-03-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_typeroomhotel_capacity_en_typeroomhotel_capacity_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='capacity_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='capacity_es',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='price_es',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='roomAvailable_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='roomAvailable_es',
        ),
    ]
