# Generated by Django 4.1.5 on 2023-03-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_reservationsrestaurant_allergy_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('fax', models.IntegerField()),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
    ]
