# Generated by Django 4.1.5 on 2023-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_hotelinformation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinformation',
            name='fax',
            field=models.CharField(max_length=11),
        ),
    ]
