# Generated by Django 4.1.5 on 2023-03-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_hotelinformation_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinformation',
            name='logo',
        ),
    ]
