# Generated by Django 4.1.5 on 2023-03-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_hotelinformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinformation',
            name='urlWeb',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
