# Generated by Django 4.1.5 on 2023-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_hotelinformation_urlweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipeTable', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('totalTable', models.IntegerField()),
            ],
        ),
    ]
