# Generated by Django 4.1.5 on 2023-01-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nombre',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.TextField(default=' ', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(max_length=30),
        ),
    ]
