# Generated by Django 4.1.5 on 2023-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservationshotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
