# Generated by Django 4.1.5 on 2023-02-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='locationBusStop',
        ),
    ]
