# Generated by Django 4.1.5 on 2023-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_location_locationbusstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeroom',
            name='roomAvailable',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeroom',
            name='type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
