# Generated by Django 4.1.5 on 2023-02-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_typeroom_roomavailable_alter_typeroom_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typeRoom',
        ),
    ]
