# Generated by Django 4.1.5 on 2023-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_typeroomhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=30)),
                ('username', models.TextField(max_length=30)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
            ],
        ),
    ]
