# Generated by Django 4.1.5 on 2023-02-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
