# Generated by Django 4.1.5 on 2023-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_promotion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationshotel',
            name='guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
