# Generated by Django 4.1.5 on 2023-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reservationshotel_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeroomhotel',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
