# Generated by Django 4.1.5 on 2023-02-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_typeroomhotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeroomhotel',
            name='namee',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
