# Generated by Django 4.1.5 on 2023-02-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_typeroomhotel_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeroomhotel',
            old_name='namee',
            new_name='name',
        ),
    ]
