# Generated by Django 4.1.5 on 2023-02-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_namee_typeroomhotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('idReservation', models.IntegerField()),
                ('price', models.IntegerField()),
                ('makeRefund', models.BooleanField()),
            ],
            options={
                'ordering': ['makeRefund'],
            },
        ),
    ]
