# Generated by Django 4.1.5 on 2023-02-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='makeRefund',
            field=models.BooleanField(default=False),
        ),
    ]
