# Generated by Django 4.1.5 on 2023-03-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_typeroomhotel_capacity_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='typeroomhotel',
            name='type_es',
        ),
    ]
