# Generated by Django 4.1.5 on 2023-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_promotion_description_en_promotion_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeroomhotel',
            name='description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='typeroomhotel',
            name='description_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='typeroomhotel',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='typeroomhotel',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
