# Generated by Django 4.1.5 on 2023-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_typeroomhotel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeroomhotel',
            name='capacityMax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeroomhotel',
            name='img',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
