# Generated by Django 4.1.5 on 2023-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_typeroomhotel_capacitymax_typeroomhotel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsrestaurant',
            name='allergy_en',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationsrestaurant',
            name='allergy_es',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationsrestaurant',
            name='email_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservationsrestaurant',
            name='email_es',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
