# Generated by Django 4.1.5 on 2023-03-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reservationsrestaurant_allergy_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationsrestaurant',
            name='allergy_en',
        ),
        migrations.RemoveField(
            model_name='reservationsrestaurant',
            name='allergy_es',
        ),
        migrations.RemoveField(
            model_name='reservationsrestaurant',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='reservationsrestaurant',
            name='email_es',
        ),
    ]
