# Generated by Django 4.1.5 on 2023-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_hotelinformation_latitude_hotelinformation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationshotel',
            name='observations',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
