# Generated by Django 4.1.5 on 2023-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_reservationshotel_observations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelinformation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reservationshotel',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='reservationsrestaurant',
            options={'ordering': ['email']},
        ),
    ]
